### ISSUE TITLE
Cards variables. Bounty Object

### ISSUE THREAD

**Issue by esteblock** [Tellus-Cooperative/bountyhunter#2]
In order to have a MVP:
Each card should have:
{
    "bounty_owner":"string", // address of the bounty owner, ex: GCZMT5BHS2HIWT2NVYPPLE5MIG7P2TUWBWLGCSMGJ7CZDQFGHMVVCVYE
    "bounty_id": "integer",
    "title":"string",
    "prize":"integer", // ex. 1000. Shoud be formated as 1,000 
    "token_code": "string", // token code. ex. USDC
    "token_id": "string", // contract id of the SAC contract, ex: ed30e33e718022f37afd836256cc99941e349664da7bef0889edbb7cdacfc107
    "description": "string",
    "longDescription": "string",
    "awarded": "bool", // if the bounty has already been awarded
    "sumbissions_number": "integer", // number of submissions
    "sumbissions": "aray[submission_object]", // See
    "winner": "integer" // Submission id of winner

},

The prize shoud be formated as {prize} {token_code}. Ex. 1,000 USDC

In the bounty image we could use the identicon service from lobstr as
https://id.lobstr.co/{bounty_owner}.png
example:
https://id.lobstr.co/GCZMT5BHS2HIWT2NVYPPLE5MIG7P2TUWBWLGCSMGJ7CZDQFGHMVVCVYE.png

If sumbissions_number>0, each bounty card should have a button "See submissions" that will display a group of Sumbissions Object's Cards

**Comment by alexanderkoh** [comment]
Cards variables completed, ID bounty image moved to #8
