### ISSUE TITLE
Apply button. Submission Object

### ISSUE THREAD

**Issue by esteblock** [Tellus-Cooperative/bountyhunter#3]
For the MVP the "Apply" button should:
- If "isConnected=false" should say "Connect Wallet to Apply"
- If "isConnected=true" should:
- Open a form
- Form should have
Some description like: "You are applying to the {issue_name} bug bounty, etc...
```
{
    "title":"string", // description: Tittle of your sollution
    "description": "string", // Describe your solution
    "github_link": "string", // Put link of your solution's repo
},
```
Button "Apply now". Dummy button. If pressed triggers a verification function.
- verify that there are no empty fields
- if ok. console.log("Applied") and close form

**Comment by Nauman440** [comment]
The form has been added and is working perfectly fine with the API

**Comment by Nauman440** [comment]
Hasura API is linked with it
