### ISSUE TITLE
My Bounties

### ISSUE THREAD

**Issue by esteblock** [Tellus-Cooperative/bountyhunter#5]
Dashboard to show user's bounties. Separated in
- My funded bounties. Filter bounties where the user is bounty_owner. 
Here, if awarded=false. Show button "Choose application... or "Award prize"??
- Display group of applications objects.
-  For each application show button "Award prize". Triggers function that will change awarded=true, and winner=application_id

- My applied bonties. Filter bounties where the user exist in applicant array.

**Comment by Nauman440** [comment]
My Bounties are showing now in the user's dashboard
